using TSPLIB

"""
    structToDict(s) -> Dict

Converts struct object to Dict.

Ref: https://stackoverflow.com/a/70317636.

## Params:
- `s::Struct`: struct obj to convert to dict.

## Returns:
- `Dict`: struct converted to dict.

"""
function structToDict(s)
  return Dict(key => getfield(s, key) for key in propertynames(s))
end

"""
    openTSPFile()

Asks for `TSP` data direcory path and filename.

Opens the file and returns a struct type generated by TSPLIB.

## Returns:
- `TSP`: struct read from file from path.

"""
function openTSPFile()
  println("Hello! Please provide full path to your data folder: ")
  path = chomp(readline())
  options = 0
  for (root, dirs, files) in walkdir(path)
    options = files
  end
  filter!(s->occursin(r".tsp", s), options)
  for el in options
    for i in 1:4 print(el, "   ") end
    println()
  end
  println()
  println("Choose a file by writing a full file name:  ")
  response = chomp(readline())
  return readTSP(path * "/" * response)
end